name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_lint_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
          POSTGRES_DB: main_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U db_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://db_user:db_password@localhost:5432/main_database?schema=public

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply database migrations
        run: npm run migrate:prod

      - name: Run unit tests
        run: npm test

      # — Descomenta este bloque si quisieras correr tests e2e también —
      #- name: Run e2e tests
      #  run: npm run test:e2e
